APP_TITILE: ${APP_TITILE}
APP_VERSION: ${APP_VERSION}

# Base de données
POSTGRES_HOST: ${POSTGRES_HOST}
POSTGRES_PORT: ${POSTGRES_PORT}
POSTGRES_DATABASE: ${POSTGRES_DATABASE}
POSTGRES_USERNAME: ${POSTGRES_USERNAME}
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

# OAuth2/JWT Configuration
JWT_SECRET: ${JWT_SECRET}
JWT_ISSUER: ${JWT_ISSUER:external-api-dev}
JWT_EXPIRATION_MINUTES: ${JWT_EXPIRATION_MINUTES:60}
JWT_REFRESH_EXPIRATION_DAYS: ${JWT_REFRESH_EXPIRATION_DAYS:7}

# Server Configuration
CONTAINER_PORT: ${CONTAINER_PORT:8090}
ACTIVE_PROFILE: ${ACTIVE_PROFILE:dev}

# Orange API Configuration
ORANGE_OAUTH_URL: ${ORANGE_OAUTH_URL}
ORANGE_OAUTH_URL_SMS: ${ORANGE_OAUTH_URL_SMS}
ORANGE_BALANCE_URL: ${ORANGE_BALANCE_URL}
ORANGE_CLIENT_CREDENTIALS: ${ORANGE_CLIENT_CREDENTIALS}
ORANGE_SENDER: ${ORANGE_SENDER}

# Selenium Configuration
SELENIUM_REMOTE_URL: ${SELENIUM_REMOTE_URL}
CHROME_REMOTE_ENABLED: ${CHROME_REMOTE_ENABLED:false}

# SMS Configuration
CODE_LIMIT: ${CODE_LIMIT:6}
EXPIRY_MINUTE: ${EXPIRY_MINUTE:10}
MAX_ATTEMPT: ${MAX_ATTEMPT:3}
LIMIT_PER_HOUR: ${LIMIT_PER_HOUR:3}
SENDER_NAME: ${SENDER_NAME}
SESSION_DURATION_DAY: ${SESSION_DURATION_DAY:10}
SMS_PRIMARY_PROVIDER: ${SMS_PRIMARY_PROVIDER:orange}

# Slack Configuration
SLACK_CREDENTIAL: ${SLACK_CREDENTIAL}